Added Convert-ObjectToHashtable fix #71
dsccommunity/DscResource.Common pull request #72
Opened 2021-05-07 16:28 UTC by NicolasBn

#### Pull Request (PR) description
- Added cmdlet `Convert-ObjectToHashtable` wich can be used to convert any object
 to hashtable. It accepts objects from pipeline.

#### This Pull Request (PR) fixes the following issues
    - Fixes #71 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2021-05-20 21:55 UTC, gaelcolas requested changes
Thanks, a few update to make.

2021-05-20 21:55 UTC, gaelcolas commented on source/Public/Convert-ObjectToHashtable.ps1
> +    }
```suggestion
    )
```

2021-05-20 21:55 UTC, gaelcolas commented on source/Public/Convert-ObjectToHashtable.ps1
> +        [Parameter(Mandatory = $true,ValueFromPipeline=$true)]
```suggestion
        [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
```

2021-05-20 21:55 UTC, gaelcolas commented on source/Public/Convert-ObjectToHashtable.ps1
> +        The object that should convert to hashtable.
```suggestion
        The object that should be converted to hashtable.
```

2021-05-20 21:55 UTC, gaelcolas commented on source/Public/Convert-ObjectToHashtable.ps1
> +        This function is used to convert an psobject into a hashtable.
```suggestion
        This function is used to convert a PSObject into a hashtable.
```

2021-05-20 21:55 UTC, gaelcolas commented on source/Public/Convert-ObjectToHashtable.ps1
> +
```suggestion

```

2021-05-20 21:55 UTC, gaelcolas commented on source/Public/Convert-ObjectToHashtable.ps1
> +
```suggestion
```

2021-05-24 13:55 UTC, NicolasBn commented
Based on suggestion of @gaelcolas, I aggregate the issue #71  and [issue 246 of Sample](https://github.com/gaelcolas/Sampler/issues/246).
I rename the function to `ConvertFrom-DscResourceInstance`.

2021-05-24 20:50 UTC, gaelcolas approved these changes

2021-05-24 20:50 UTC, gaelcolas commented on source/Public/ConvertFrom-DscResourceInstance.ps1
> +    )
```suggestion
    )

```

2021-05-24 20:50 UTC, merged

2021-06-07 15:31 UTC, johlju commented
We should have updated documentation in the README.md as well. I add an issue to track it.